version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/github.com/hirokazutei
    steps:
      - checkout
      - run: go get -v -t
      - run: go build -v
