"""generating database schema

Revision ID: 00e9f3d6a5e0
Revises: 
Create Date: 2019-03-21 17:00:33.822034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e9f3d6a5e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artiefact_user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('salt', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('register_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artiefact_user_status'), 'artiefact_user', ['status'], unique=False)
    op.create_table('profile',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('website', sa.TEXT(), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('gender', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['artiefact_user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('profile_picture',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('thumbnail', sa.TEXT(), nullable=True),
    sa.Column('image', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['artiefact_user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_agreement',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('agreement_type', sa.TEXT(), nullable=False),
    sa.Column('agreement_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['artiefact_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('username',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('username_lower', sa.TEXT(), nullable=False),
    sa.Column('username_raw', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['artiefact_user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_username_username_lower'), 'username', ['username_lower'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_username_username_lower'), table_name='username')
    op.drop_table('username')
    op.drop_table('user_agreement')
    op.drop_table('profile_picture')
    op.drop_table('profile')
    op.drop_index(op.f('ix_artiefact_user_status'), table_name='artiefact_user')
    op.drop_table('artiefact_user')
    # ### end Alembic commands ###
