"""Added Saga, Story and LocationBatch

Revision ID: 2e3e901d85cd
Revises: f9c8e15907ea
Create Date: 2019-04-24 02:36:57.861963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e3e901d85cd'
down_revision = 'f9c8e15907ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saga',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('begin_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starting_longitudes', sa.NUMERIC(), nullable=False),
    sa.Column('starting_latitudes', sa.NUMERIC(), nullable=False),
    sa.Column('ending_longitudes', sa.NUMERIC(), nullable=True),
    sa.Column('ending_latitudes', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saga_user_id'), 'saga', ['user_id'], unique=False)
    op.create_table('chapter',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('saga_id', sa.BIGINT(), nullable=False),
    sa.Column('begin_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starting_longitudes', sa.NUMERIC(), nullable=False),
    sa.Column('starting_latitudes', sa.NUMERIC(), nullable=False),
    sa.Column('ending_longitudes', sa.NUMERIC(), nullable=True),
    sa.Column('ending_latitudes', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['saga_id'], ['saga.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking_batch',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('chapter', sa.BIGINT(), nullable=False),
    sa.Column('longitudes', postgresql.ARRAY(sa.NUMERIC()), nullable=True),
    sa.Column('latitudes', postgresql.ARRAY(sa.NUMERIC()), nullable=True),
    sa.ForeignKeyConstraint(['chapter'], ['chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking_batch')
    op.drop_table('chapter')
    op.drop_index(op.f('ix_saga_user_id'), table_name='saga')
    op.drop_table('saga')
    # ### end Alembic commands ###
