"""Added User/Username/Profile/ProfilePicture

Revision ID: 55fcd87a0a50
Revises: 
Create Date: 2019-03-13 23:38:22.756960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55fcd87a0a50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('register_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    op.create_table('profile',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('website', sa.TEXT(), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('gender', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('profile picture',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('thumbnail', sa.TEXT(), nullable=True),
    sa.Column('image', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_agreement',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('agreement_type', sa.TEXT(), nullable=False),
    sa.Column('agreement_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('username',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('lower_name', sa.TEXT(), nullable=False),
    sa.Column('display_name', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_username_lower_name'), 'username', ['lower_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_username_lower_name'), table_name='username')
    op.drop_table('username')
    op.drop_table('user_agreement')
    op.drop_table('profile picture')
    op.drop_table('profile')
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
