"""Autogenerating database tables

Revision ID: 9a82f5b922cb
Revises: 
Create Date: 2019-06-15 16:14:03.351246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a82f5b922cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token',
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('generated_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('obtained_by', sa.TEXT(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_access_token_token'), 'access_token', ['token'], unique=False)
    op.create_index(op.f('ix_access_token_user_id'), 'access_token', ['user_id'], unique=False)
    op.create_table('artiefact_user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('register_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artiefact_user_status'), 'artiefact_user', ['status'], unique=False)
    op.create_table('profile',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('website', sa.TEXT(), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('gender', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['artiefact_user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('profile_picture',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('thumbnail', sa.TEXT(), nullable=True),
    sa.Column('image', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['artiefact_user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('registered_email',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('email_lower', sa.TEXT(), nullable=False),
    sa.Column('last_used_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['artiefact_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registered_email_id'), 'registered_email', ['id'], unique=False)
    op.create_index(op.f('ix_registered_email_user_id'), 'registered_email', ['user_id'], unique=False)
    op.create_table('token_access',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('last_used_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token'], ['access_token.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_agreement',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('agreement_type', sa.TEXT(), nullable=False),
    sa.Column('agreement_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['artiefact_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('username',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('username_lower', sa.TEXT(), nullable=False),
    sa.Column('username_raw', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['artiefact_user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_username_username_lower'), 'username', ['username_lower'], unique=True)
    op.create_table('email_verification_request',
    sa.Column('registered_email_id', sa.BIGINT(), nullable=False),
    sa.Column('code', sa.TEXT(), nullable=False),
    sa.Column('expiration_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['registered_email_id'], ['registered_email.id'], ),
    sa.PrimaryKeyConstraint('registered_email_id')
    )
    op.create_table('email_verification',
    sa.Column('request_id', sa.BIGINT(), nullable=False),
    sa.Column('verification_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['email_verification_request.registered_email_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_verification')
    op.drop_table('email_verification_request')
    op.drop_index(op.f('ix_username_username_lower'), table_name='username')
    op.drop_table('username')
    op.drop_table('user_agreement')
    op.drop_table('token_access')
    op.drop_index(op.f('ix_registered_email_user_id'), table_name='registered_email')
    op.drop_index(op.f('ix_registered_email_id'), table_name='registered_email')
    op.drop_table('registered_email')
    op.drop_table('profile_picture')
    op.drop_table('profile')
    op.drop_index(op.f('ix_artiefact_user_status'), table_name='artiefact_user')
    op.drop_table('artiefact_user')
    op.drop_index(op.f('ix_access_token_user_id'), table_name='access_token')
    op.drop_index(op.f('ix_access_token_token'), table_name='access_token')
    op.drop_table('access_token')
    # ### end Alembic commands ###
