"""made some changes to username

Revision ID: a94bb985e07f
Revises: 55fcd87a0a50
Create Date: 2019-03-16 14:51:50.405565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94bb985e07f'
down_revision = '55fcd87a0a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('username', sa.Column('username_lower', sa.TEXT(), nullable=False))
    op.add_column('username', sa.Column('username_raw', sa.TEXT(), nullable=False))
    op.create_index(op.f('ix_username_username_lower'), 'username', ['username_lower'], unique=True)
    op.drop_index('ix_username_lower_name', table_name='username')
    op.drop_column('username', 'display_name')
    op.drop_column('username', 'lower_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('username', sa.Column('lower_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('username', sa.Column('display_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index('ix_username_lower_name', 'username', ['lower_name'], unique=True)
    op.drop_index(op.f('ix_username_username_lower'), table_name='username')
    op.drop_column('username', 'username_raw')
    op.drop_column('username', 'username_lower')
    # ### end Alembic commands ###
