"""fixing database

Revision ID: f171545d6295
Revises: a94bb985e07f
Create Date: 2019-03-16 15:17:08.628567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f171545d6295'
down_revision = 'a94bb985e07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_picture',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('thumbnail', sa.TEXT(), nullable=True),
    sa.Column('image', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('profile picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile picture',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('thumbnail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='profile picture_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='profile picture_pkey')
    )
    op.drop_table('profile_picture')
    # ### end Alembic commands ###
