"""autogenerating database schema

Revision ID: f9c8e15907ea
Revises: 
Create Date: 2019-03-23 19:02:43.387252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c8e15907ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token',
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('generated_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('obtained_by', sa.TEXT(), nullable=False),
    sa.Column('token_type', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_access_token_user_id'), 'access_token', ['user_id'], unique=False)
    op.create_table('artiefact_user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('register_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artiefact_user_status'), 'artiefact_user', ['status'], unique=False)
    op.create_table('profile',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('website', sa.TEXT(), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('gender', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['artiefact_user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('profile_picture',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('thumbnail', sa.TEXT(), nullable=True),
    sa.Column('image', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['artiefact_user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('token_access',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('last_used_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token'], ['access_token.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_agreement',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('agreement_type', sa.TEXT(), nullable=False),
    sa.Column('agreement_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['artiefact_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('username',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('username_lower', sa.TEXT(), nullable=False),
    sa.Column('username_raw', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['artiefact_user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_username_username_lower'), 'username', ['username_lower'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_username_username_lower'), table_name='username')
    op.drop_table('username')
    op.drop_table('user_agreement')
    op.drop_table('token_access')
    op.drop_table('profile_picture')
    op.drop_table('profile')
    op.drop_index(op.f('ix_artiefact_user_status'), table_name='artiefact_user')
    op.drop_table('artiefact_user')
    op.drop_index(op.f('ix_access_token_user_id'), table_name='access_token')
    op.drop_table('access_token')
    # ### end Alembic commands ###
